# Generated by Django 3.1.7 on 2021-04-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedBlueapp', '0002_delete_nifty50'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nifty50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('d_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema26', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema13', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema05', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('d_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('macd_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('macd_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vol_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'nifty50',
                'managed': False,
            },
        ),
    ]
